### ISSUE TITLE
Problema 24: calcular e imprimir una tabla de dos columnas que muestre, en la primera,los enteros del 1 al n, y en la segunda n^2. No utilizar un entero mayor que 30 para n.

### ISSUE THREAD

**Issue by Hector1502** [PFLC/py302#23]
¿Se pueden hacer tablas usando Python en PyCharm? ¿Alguien sabe cómo? :(

**Comment by renesolis** [comment]
Puede usar un print con espacio, desplegando en ese mismo los 2 valores, al final seran visiblemente 2 columnas.. !!
